<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1538280599223" stop="1538280599346">
  <name>test01</name>
  <labels/>
  <test-cases>
    <test-case start="1538280599223" status="passed" stop="1538280599227">
      <name>Test01.test01</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="25599-MainThread"/>
        <label name="host" value="1deMacBook-Pro.local"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps>
        <step start="1538280599226" status="passed" stop="1538280599226">
          <name>执行学院新增操作</name>
          <title>执行学院新增操作</title>
          <attachments/>
          <steps/>
        </step>
      </steps>
    </test-case>
    <test-case start="1538280599229" status="failed" stop="1538280599329">
      <name>Test01.test02</name>
      <failure>
        <message>AssertionError: assert False</message>
        <stack-trace>self = &lt;test01.Test01 object at 0x103b8bf28&gt;

    @allure.step("执行学院更新操作")
    
    @pytest.allure.severity(pytest.allure.severity_level.BLOCKER)
    def test02(self):
        allure.attach("断言开始","学院是否更新成功")
        print("执行学院更新操作")
        allure.attach("断言结束","更新成功！")
&gt;       assert False
E       assert False

Scripts/test01.py:16: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="blocker"/>
        <label name="thread" value="25599-MainThread"/>
        <label name="host" value="1deMacBook-Pro.local"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps>
        <step start="1538280599230" status="failed" stop="1538280599232">
          <name>执行学院更新操作</name>
          <title>执行学院更新操作</title>
          <attachments>
            <attachment source="6262e75d-59fc-4b59-9c57-cdadc923e4e5-attachment.txt" title="断言开始" type="text/plain"/>
            <attachment source="75c26989-2fe5-4196-a23b-4a2a4da2dfc3-attachment.txt" title="断言结束" type="text/plain"/>
          </attachments>
          <steps/>
        </step>
        <step start="1538280599326" status="failed" stop="1538280599326">
          <name>执行学院更新操作</name>
          <title>执行学院更新操作</title>
          <attachments>
            <attachment source="8e9b8590-df24-4b2f-97da-7db4dd75a99b-attachment.txt" title="断言开始" type="text/plain"/>
            <attachment source="07c3f69d-6204-45d9-8a1e-38128c9dceb3-attachment.txt" title="断言结束" type="text/plain"/>
          </attachments>
          <steps/>
        </step>
      </steps>
    </test-case>
    <test-case start="1538280599334" status="failed" stop="1538280599346">
      <name>Test01.test03</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;test01.Test01 object at 0x103bd19e8&gt;

    @pytest.allure.severity(pytest.allure.severity_level.CRITICAL)
    def test03(self):
        print("test03被执行")
&gt;       assert 0
E       assert 0

Scripts/test01.py:21: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="critical"/>
        <label name="thread" value="25599-MainThread"/>
        <label name="host" value="1deMacBook-Pro.local"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
